x-app: &app
  restart: unless-stopped

services:
  postgres:
    image: postgres:16
    container_name: empolimer-postgres
    <<: *app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

  redis:
    image: redis:6
    container_name: empolimer-redis
    <<: *app
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/aleksioprime/empolimer-backend:${BACKEND_IMAGE_TAG:-latest}
    container_name: empolimer-backend
    <<: *app
    command: python src/main.py
    volumes:
      - media:/usr/src/app/media
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  worker:
    image: ghcr.io/aleksioprime/empolimer-worker:${WORKER_IMAGE_TAG:-latest}
    container_name: empolimer-worker
    <<: *app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: ghcr.io/aleksioprime/empolimer-frontend:${FRONTEND_IMAGE_TAG:-latest}
    <<: *app
    container_name: empolimer-frontend
    volumes:
      - media:/usr/share/nginx/html/media
    depends_on:
      backend:
        condition: service_started

  adminer:
    image: adminer
    container_name: empolimer-adminer
    <<: *app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  media:
  postgres_volume:
  redis_volume: